### ISSUE TITLE
We need to think how to limit users access revocation when onboarding 

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/terraform-aws-sso-elevator#14]
Before sso elevator would only revoke user assignments in accounts specified in the configuration - how it affects the whole organization. we need to think about how we could let people choose what accounts to onboard. Is there a possibility to tag accounts?

**Comment by cageyv** [comment]
`aws_organizations_account` supports tagging , so it is possible to tag accounts 
maybe `"sso-elevator:skip = true"` or etc 
But in that case we probably should skip all actions against that account, I mean both adding and removing permissions
It will allow to roll out sso-elevator account by account

**Comment by Andrey9kin** [comment]
Yeah, been thinking along those lines. Though I would do it in the opposite way. Have a variable that would tell lambdas to only manage a list of tagged accounts, if the list is empty - manage everything and ignore tags. So in this way, tags will tell what accounts to manage, not to skip. The logic behind it - you want to try only one account in the begging so you tag only that account to be managed. Otherwise, you would have to tag all accounts you do not want to manage which is not very user-friendly.

**Comment by EreminAnton** [comment]
Seems like we choosing between whitelist & blacklist.
The elevator now only work with the accounts specified in the 'Resource' fields. It can only create or revoke account assignments for those accounts. However, if a user enters a '*' in the 'Resource' field anywhere in the configuration, for example when creating an organization-wide approver, this means that the elevator will now show all accounts in the menu and will be able to create or remove account assignments for the entire organization.

So users can already create a whitelist by filling in the 'Resource' configuration fields without '*'. And only if the user wants to use '*' but exclude some accounts, a blacklist can be usefull.

A blacklist can be implemented using lambda variables in Terraform or by using account tagging. Using Terraform seems like a quicker choice, as it eliminates the need to make API calls to check tags for all accounts every time we work with them.

About revoking account assginments:
	What can revoke?

1.  Everything: Using a cron revoke, Elevator will delete all account assignments in all accounts specified in the configuration (if '*' is used in the "Resource" field, it will revoke all assignments in the entire organization). This can be a useful security feature, and a blacklist can be used if the user wants to avoid revoking certain account assignments.

2.  Only managed: This can be implemented by making the cron revoke optional and turning it off. Elevator will only delete the account assignments that it has created and scheduled. Inconsistencies can be detected by using EventBrige as state, and we can add an alert to post to Slack, and the user can be given buttons to remove or keep all inconsistencies.

3.  Only unmanaged: This also requires an optional cron revoke. In this case also we can use EventBridge  as state, then we can list all account assignments across the organization and remove everything that is not in the state. All other assignments will be removed according to the existing schedule. Similar to option 2, an alert can be added to post to Slack for any inconsistencies.

And all three features can be realised at the same time, but just be optional.

**Comment by Andrey9kin** [comment]
Ok, it is good enough if we can still control what accounts will get managed by not specifying * for all accounts. No action needed
