### ISSUE TITLE
Consistency check messages are not very useful

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/terraform-aws-sso-elevator#31]
- [ ] Messages need to contain more information
- [ ] Post one message with all inconsistencies found instead of a message of each inconsistency

**Comment by EreminAnton** [comment]
Looks like [duplicate](https://github.com/fivexl/terraform-aws-sso-elevator/issues/29),
If it would be safe to post this to slack, we can add the following information:
class AccountAssignment:
    account_id: str
    permission_set_arn: str
    principal_id: str
    principal_type: str
