### ISSUE TITLE
Audit logs for automated revokation has no info about which assignment was revoked

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/terraform-aws-sso-elevator#32]
for assignment creation we log requester and approver data but for revocation there is none
Would be good to look requester data - person for whom assignment has been revoked
Plus it would be good to extend log data and log sso assignment id as well

**Comment by Andrey9kin** [comment]
Looks like I checked old records, new records look fine. though would be good to log the assignment id

**Comment by EreminAnton** [comment]
looks like [account assignment](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/list_account_assignments.html) does not have id:
```
{
    'AccountAssignments': [
        {
            'AccountId': 'string',
            'PermissionSetArn': 'string',
            'PrincipalType': 'USER'|'GROUP',
            'PrincipalId': 'string'
        },
    ],
    'NextToken': 'string'
}
```
Create some id myself?

**Comment by Andrey9kin** [comment]
No, I now remember, that indeed there are no ids for the account assignments. Ignore this
