### ISSUE TITLE
Random error from slack

### ISSUE THREAD

**Issue by EreminAnton** [fivexl/terraform-aws-sso-elevator#36]
Retry show initial form helps.
{
    "level": "ERROR",
    "location": "request_wired_func_wrapper:30",
    "message": "Failed to run an internal function ('5207005875042.864444445072.8c5e89b0a7ef8b67ad1196d6b04e5bc1')",
    "timestamp": "2023-05-11 07:53:17,049+0000",
    "service": "slack",
    "xray_trace_id": "1-142c9er7-28a7e9cd7d707edc31a591e2"
}

**Comment by Andrey9kin** [comment]
Close as inactive. Re-open if re-appears
