### ISSUE TITLE
Lambda searches only inside of first 100 sso users

### ISSUE THREAD

**Issue by oleksandrsv** [fivexl/terraform-aws-sso-elevator#65]
Hi, we found a bug when lambda is searching only inside first 100 users in identity store.
In response we managed to find a 'next token' so function should have pagination.

`'IdentityStoreId': 'd-123456789'}], 'NextToken': 'abc..xyz', 'ResponseMetadata': {'RequestId': '123-456-789', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Thu, 30 Nov 2023 10:21:21 GMT', 'content-type': 'application/x-amz-json-1.1', 'content-length': '30019', 'connection': 'keep-alive', 'x-amzn-requestid': '123-456-789'}, 'RetryAttempts': 0}}
`

**Comment by Andrey9kin** [comment]
@EreminAnton please take a look. @oleksandrsv thanks for reporting!

**Comment by EreminAnton** [comment]
Hello @oleksandrsv, thank you for reporting this issue! We have created a new release that includes pagination. Please check and let us know if the issue has been resolved.

**Comment by oleksandrsv** [comment]
I can confirm, that it works (after lambda was destroyed and created from scratch).

**Comment by EreminAnton** [comment]
Thanks for the update! I'm closing this issue now. If you encounter any more issues, please feel free to reach out.
