### ISSUE TITLE
Fix initial CodeGuru findings

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/terraform-aws-sso-elevator#73]
https://github.com/fivexl/terraform-aws-sso-elevator/security/code-scanning

https://github.com/fivexl/terraform-aws-sso-elevator/security/secret-scanning/1

**Comment by EreminAnton** [comment]
- Removed Slack Webhook from the initial commit history
- Small fixes to adress other alerts
- Postponed fixing of timezone issues because of task complexity. Created separate issue to track it.
