### ISSUE TITLE
Terraform Cloud

### ISSUE THREAD

**Issue by dash-aug** [fivexl/terraform-aws-sso-elevator#75]
Module can't be used with terraform cloud as neither docker nor the correct python version are available. Perhaps shipping a zip file for each lambda might be a more portable option.

**Comment by dash-aug** [comment]
@EreminAnton No worries, I found a solution by deploying a custom TFC agent that has the python version required installed. However, others might not have the chance to do it this way. 

The way i'd see this change happen is to bundle the source code at release time and then just commit it back to the repo and refactor the lambdas to refer to those .zip files created. YMMV, just thought I'd share this of the top of my head.

**Comment by Andrey9kin** [comment]
There is another problem with building zip files locally—at times; it fails to fetch deps if the Python version requirements aren't met and give no warning.
Let's build zip files in CI and update terraform to fetch pre-built files from CDN with the possibility to fallback to the local build

**Comment by Andrey9kin** [comment]
This will also address #64

**Comment by Andrey9kin** [comment]
Or even better - publish deps as a public layer and app itself as a public layer or to GitHub ECR

**Comment by Andrey9kin** [comment]
@dash-aug, we implemented the use of pre-build docker images that should remove all build requirements from the machine where you run Terraform
We are going to test new release today and next week to iron out all the bugs and then it is ready to be tried
