### ISSUE TITLE
SecurityHub is unhappy with Lambda URL

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/terraform-aws-sso-elevator#81]

**Comment by Andrey9kin** [comment]
First research what exactly is the problem suggested by SecurityHub. The current best thinking is that it is unhappy with the fact that anyone can call Lambda URL

**Comment by EreminAnton** [comment]
Security hub was unhappy with the FunctionURLAllowPublicAccess that is created after lambda url creation by the aws_lambda_function_url resource creation. 

Adressed by allowing to use API Gateway instead of Lambda URL

https://github.com/hashicorp/terraform-provider-aws/issues/38260
